spring.data.mongodb.uri=mongodb+srv://braincode16211_db_user:<password>@get4u.xhjj89f.mongodb.net/?appName=get4u
spring.data.mongodb.database=get4udb
spring.data.mongodb.auto-index-creation=true
//  MongoDB connection settings